export const ROUTES = {
  HOME: '/',
  MERI_FASAL: '/meri-fasal',
  SOIL_TESTING: '/soil-testing',
  CROP_DETAIL: (id: string | number = ':cropId') => `/meri-fasal/${id}`,
  WEATHER: '/weather',
  MARKET: '/market',
  MARKET_DETAIL: (id: string | number = ':marketId') => `/market/${id}`,
  MARKETPLACE: '/marketplace',
  RISK: '/risk',
  ASSISTANT: '/assistant',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  ONBOARDING: '/onboarding',
  LANGUAGE_SELECT: '/language',
  LOGIN: '/login',
  REGISTER: '/register',
} as const;
